config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  GUESTSNUMBER = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

  validates :name, :address, :description, presence: true
  validates :price_per_night, numericality: true
  validates :number_of_guests, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end

  end

  def new
    @flat = Flat.new
  end

  def edit

  end

  def show
    @flat = Flat.find(params[:id])
  end

  def update

  end

  def destroy

  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests, collection: Flat::GUESTSNUMBER %>

    <%= f.submit %>
  <% end %>

app/views/flats/index.html.erb
<nav class="navbar sticky-top navbar-light bg-light">
  <span class="navbar-brand m-1 h1">Simple Airbnb</span>
  <a class="nav-link my-2 my-sm-0" <%= link_to "Add Airbnb", new_flat_path %></a>
</nav>

<h1>All Our Flats Available (<%= @flats.length %>)</h1>

<div class="mb-10">
  <div class="d-flex row">
  <% @flats.each do |flat| %>
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to flat.name, flat_path(flat) %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= flat.address %></h6>
          <p class="card-text"><%= flat.description %></p>
          <i class="fa-solid fa-person-dress"> <%= flat.number_of_guests %> </i>
          <i class="fa-solid fa-euro-sign"> <%= flat.price_per_night %> </i>
          <div class="card-footer">
            <small class="text-muted"><%= link_to "More Info", flat_path(flat) %></small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add New Flat</h1>
  <%= render 'form' %>

  <hr>

  <%= link_to "Back to Home", flats_path %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <h1><%= @flat.name %></h1>
  <strong>Address: </strong> <%= @flat.address %><br>
  <strong>Category: </strong> <%= @flat.description %><br>
  <strong>Price per night: </strong><%= @flat.price_per_night %>
  <strong>No. of Guest: </strong><%= @flat.number_of_guests %>

  <hr>

  <%= link_to "Back to Home", flats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>

  </body>
</html>